config/routes.rb
Rails.application.routes.draw do
  resources :securitys_transactions
  resources :securitys_closing_prices
  resources :securities
  resources :cash_transactions
  resources :funds
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/fundos', to: 'funds#index'
  get '/transacaoCaixa', to: 'cash_transactions#index'
  get '/ativos', to: 'securities#index'

  get '/precoAtivos/:id/:date', to: 'securitys_closing_prices#getPrice'
  get '/precoAtivos/:id', to: 'securitys_closing_prices#getPrice'
  get '/precoAtivos', to: 'securitys_closing_prices#index'

  get '/transacaoAtivos', to: 'securitys_transactions#index'
  get "/precos/historico", to: "securitys_closing_prices#index"
  
  #portifolio

  #obter transacoes de caixa por fundo
  get "/portifolios/saldo/:id/:date", to: "portifolios#totalCashTransactions"
  get "/portifolios/saldo/:id", to: "portifolios#totalCashTransactions"
  get "/portifolios/transacoes/:id", to: "portifolios#listTransactionsByFund"
  get "/portifolios/transacoes/:id/:date", to: "portifolios#listTransactionsByFund"

  #obter ativos por fundo
  get "/portifolios/ativos/:id/:date", to: "portifolios#totalAtivos"
  get "/portifolios/ativos/:id", to: "portifolios#totalAtivos"

  #obter pl por fundo
  get "/portifolios/pl/:id/:date", to: "portifolios#PLfund"
  get "/portifolios/pl/:id", to: "portifolios#PLfund"
end

app/models/securitys_closing_price.rb
class SecuritysClosingPrice < ApplicationRecord
  belongs_to :security

  def self.sendPrice(security_id, date) 
    all
      .select("security_id, closing_price, date_closing")
      .where(security_id: security_id)
      .where("date_closing <= ?", date)
      .order("date_closing desc")
      .limit(1)
      .as_json(only: :closing_price)
  end

  def self.sendPriceClose(security_id, date) 
    price = all
      .select("security_id, closing_price, date_closing")
      .where(security_id: security_id)
      .where("date_closing <= ?", date)
      .order("date_closing desc")
      .limit(1)
    return price.first.closing_price
  end

  def self.closingPrices 
    all
      .select("id, closing_price, date_closing, security_id")
      .includes(:security)
      .as_json(include: {security: {only: [:security_simbol]}})
  end
  

  def self.shift_date(date) 
    while (date.saturday? || date.sunday?)
      date -= 1 
    end
    return date
  end

end

app/controllers/securitys_closing_prices_controller.rb
class SecuritysClosingPricesController < ApplicationController
  before_action :set_securitys_closing_price, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  # GET /securitys_closing_prices or /securitys_closing_prices.json
  def index
    render json: SecuritysClosingPrice.closingPrices
  end

  def getPrice
    date = params[:date] ? params[:date] : Date.yesterday

    render json: SecuritysClosingPrice.sendPrice(params[:id], date); 
  end

  # GET /securitys_closing_prices/1 or /securitys_closing_prices/1.json
  def show
  end

  # GET /securitys_closing_prices/new
  def new
    @securitys_closing_price = SecuritysClosingPrice.new
  end

  # GET /securitys_closing_prices/1/edit
  def edit
  end

  # POST /securitys_closing_prices or /securitys_closing_prices.json
  def create
    @securitys_closing_price = SecuritysClosingPrice.new(securitys_closing_price_params)

    respond_to do |format|
      if @securitys_closing_price.save
        format.html { redirect_to securitys_closing_price_url(@securitys_closing_price), notice: "Securitys closing price was successfully created." }
        format.json { render :show, status: :created, location: @securitys_closing_price }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @securitys_closing_price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /securitys_closing_prices/1 or /securitys_closing_prices/1.json
  def update
    respond_to do |format|
      if @securitys_closing_price.update(securitys_closing_price_params)
        format.html { redirect_to securitys_closing_price_url(@securitys_closing_price), notice: "Securitys closing price was successfully updated." }
        format.json { render :show, status: :ok, location: @securitys_closing_price }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @securitys_closing_price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /securitys_closing_prices/1 or /securitys_closing_prices/1.json
  def destroy
    @securitys_closing_price.destroy

    respond_to do |format|
      format.html { redirect_to securitys_closing_prices_url, notice: "Securitys closing price was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_securitys_closing_price
      @securitys_closing_price = SecuritysClosingPrice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def securitys_closing_price_params
      params.require(:securitys_closing_price).permit(:closing_price, :date_closing, :security_id)
    end
end

app/helpers/securitys_closing_prices_helper.rb
module SecuritysClosingPricesHelper
end

app/views/securitys_closing_prices/_form.html.erb
<%= form_with(model: securitys_closing_price) do |form| %>
  <% if securitys_closing_price.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(securitys_closing_price.errors.count, "error") %> prohibited this securitys_closing_price from being saved:</h2>

      <ul>
        <% securitys_closing_price.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :closing_price, style: "display: block" %>
    <%= form.text_field :closing_price %>
  </div>

  <div>
    <%= form.label :date_closing, style: "display: block" %>
    <%= form.date_field :date_closing %>
  </div>

  <div>
    <%= form.label :security_id, style: "display: block" %>
    <%= form.number_field :security_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/securitys_closing_prices/_securitys_closing_price.html.erb
<div id="<%= dom_id securitys_closing_price %>">
  <p>
    <strong>Closing price:</strong>
    <%= securitys_closing_price.closing_price %>
  </p>

  <p>
    <strong>Date closing:</strong>
    <%= securitys_closing_price.date_closing %>
  </p>

  <p>
    <strong>Security:</strong>
    <%= securitys_closing_price.security_id %>
  </p>

</div>

app/views/securitys_closing_prices/edit.html.erb
<h1>Editing securitys closing price</h1>

<%= render "form", securitys_closing_price: @securitys_closing_price %>

<br>

<div>
  <%= link_to "Show this securitys closing price", @securitys_closing_price %> |
  <%= link_to "Back to securitys closing prices", securitys_closing_prices_path %>
</div>

app/views/securitys_closing_prices/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Securitys closing prices</h1>

<div id="securitys_closing_prices">
  <% @securitys_closing_prices.each do |securitys_closing_price| %>
    <%= render securitys_closing_price %>
    <p>
      <%= link_to "Show this securitys closing price", securitys_closing_price %>
    </p>
  <% end %>
</div>

<%= link_to "New securitys closing price", new_securitys_closing_price_path %>

app/views/securitys_closing_prices/new.html.erb
<h1>New securitys closing price</h1>

<%= render "form", securitys_closing_price: @securitys_closing_price %>

<br>

<div>
  <%= link_to "Back to securitys closing prices", securitys_closing_prices_path %>
</div>

app/views/securitys_closing_prices/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @securitys_closing_price %>

<div>
  <%= link_to "Edit this securitys closing price", edit_securitys_closing_price_path(@securitys_closing_price) %> |
  <%= link_to "Back to securitys closing prices", securitys_closing_prices_path %>

  <%= button_to "Destroy this securitys closing price", @securitys_closing_price, method: :delete %>
</div>