config/routes.rb
Rails.application.routes.draw do
  resources :securitys_transactions
  resources :securitys_closing_prices
  resources :securities
  resources :cash_transactions
  resources :funds
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/fundos', to: 'funds#index'
  get '/transacaoCaixa', to: 'cash_transactions#index'
  get '/ativos', to: 'securities#index'

  get '/precoAtivos/:id/:date', to: 'securitys_closing_prices#getPrice'
  get '/precoAtivos/:id', to: 'securitys_closing_prices#getPrice'
  get '/precoAtivos', to: 'securitys_closing_prices#index'

  get '/transacaoAtivos', to: 'securitys_transactions#index'
  get "/precos/historico", to: "securitys_closing_prices#index"
  
  #portifolio

  #obter transacoes de caixa por fundo
  get "/portifolios/saldo/:id/:date", to: "portifolios#totalCashTransactions"
  get "/portifolios/saldo/:id", to: "portifolios#totalCashTransactions"
  get "/portifolios/transacoes/:id", to: "portifolios#listTransactionsByFund"
  get "/portifolios/transacoes/:id/:date", to: "portifolios#listTransactionsByFund"

  #obter ativos por fundo
  get "/portifolios/ativos/:id/:date", to: "portifolios#totalAtivos"
  get "/portifolios/ativos/:id", to: "portifolios#totalAtivos"

  #obter pl por fundo
  get "/portifolios/pl/:id/:date", to: "portifolios#PLfund"
  get "/portifolios/pl/:id", to: "portifolios#PLfund"
end

app/models/security.rb
class Security < ApplicationRecord
  has_many :securitys_closing_prices
  has_many :securitys_transactions


  def as_json(_option)
    super({
      only: [:id, :security_simbol, :security_desc, :creation_date]  
    });
  end
end

app/controllers/securities_controller.rb
class SecuritiesController < ApplicationController
  before_action :set_security, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  # GET /securities or /securities.json
  def index
    render json:  Security.all
  end

  # GET /securities/1 or /securities/1.json
  def show
  end

  # GET /securities/new
  def new
    @security = Security.new
  end

  # GET /securities/1/edit
  def edit
  end

  # POST /securities or /securities.json
  def create
    @security = Security.new(security_params)

    respond_to do |format|
      if @security.save
        format.html { redirect_to security_url(@security), notice: "Security was successfully created." }
        format.json { render :show, status: :created, location: @security }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @security.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /securities/1 or /securities/1.json
  def update
    respond_to do |format|
      if @security.update(security_params)
        format.html { redirect_to security_url(@security), notice: "Security was successfully updated." }
        format.json { render :show, status: :ok, location: @security }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @security.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /securities/1 or /securities/1.json
  def destroy
    @security.destroy

    respond_to do |format|
      format.html { redirect_to securities_url, notice: "Security was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_security
      @security = Security.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def security_params
      params.require(:security).permit(:security_simbol, :creation_date, :security_desc)
    end
end

app/helpers/securities_helper.rb
module SecuritiesHelper
end

app/views/securities/_form.html.erb
<%= form_with(model: security) do |form| %>
  <% if security.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(security.errors.count, "error") %> prohibited this security from being saved:</h2>

      <ul>
        <% security.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :security_simbol, style: "display: block" %>
    <%= form.text_field :security_simbol %>
  </div>

  <div>
    <%= form.label :creation_date, style: "display: block" %>
    <%= form.date_field :creation_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/securities/_security.html.erb
<div id="<%= dom_id security %>">
  <p>
    <strong>Security simbol:</strong>
    <%= security.security_simbol %>
  </p>

  <p>
    <strong>Creation date:</strong>
    <%= security.creation_date %>
  </p>

</div>

app/views/securities/edit.html.erb
<h1>Editing security</h1>

<%= render "form", security: @security %>

<br>

<div>
  <%= link_to "Show this security", @security %> |
  <%= link_to "Back to securities", securities_path %>
</div>

app/views/securities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Securities</h1>

<div id="securities">
  <% @securities.each do |security| %>
    <%= render security %>
    <p>
      <%= link_to "Show this security", security %>
    </p>
  <% end %>
</div>

<%= link_to "New security", new_security_path %>

app/views/securities/new.html.erb
<h1>New security</h1>

<%= render "form", security: @security %>

<br>

<div>
  <%= link_to "Back to securities", securities_path %>
</div>

app/views/securities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @security %>

<div>
  <%= link_to "Edit this security", edit_security_path(@security) %> |
  <%= link_to "Back to securities", securities_path %>

  <%= button_to "Destroy this security", @security, method: :delete %>
</div>