config/routes.rb
Rails.application.routes.draw do
  resources :securitys_transactions
  resources :securitys_closing_prices
  resources :securities
  resources :cash_transactions
  resources :funds
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/fundos', to: 'funds#index'
  get '/transacaoCaixa', to: 'cash_transactions#index'
  get '/ativos', to: 'securities#index'

  get '/precoAtivos/:id/:date', to: 'securitys_closing_prices#getPrice'
  get '/precoAtivos/:id', to: 'securitys_closing_prices#getPrice'
  get '/precoAtivos', to: 'securitys_closing_prices#index'

  get '/transacaoAtivos', to: 'securitys_transactions#index'
  get "/precos/historico", to: "securitys_closing_prices#index"
  
  #portifolio

  #obter transacoes de caixa por fundo
  get "/portifolios/saldo/:id/:date", to: "portifolios#totalCashTransactions"
  get "/portifolios/saldo/:id", to: "portifolios#totalCashTransactions"
  get "/portifolios/transacoes/:id", to: "portifolios#listTransactionsByFund"
  get "/portifolios/transacoes/:id/:date", to: "portifolios#listTransactionsByFund"

  #obter ativos por fundo
  get "/portifolios/ativos/:id/:date", to: "portifolios#totalAtivos"
  get "/portifolios/ativos/:id", to: "portifolios#totalAtivos"

  #obter pl por fundo
  get "/portifolios/pl/:id/:date", to: "portifolios#PLfund"
  get "/portifolios/pl/:id", to: "portifolios#PLfund"
end

app/controllers/securitys_transactions_controller.rb
class SecuritysTransactionsController < ApplicationController
  before_action :set_securitys_transaction, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  # GET /securitys_transactions or /securitys_transactions.json
  def index
    render json: SecuritysTransaction.transactions
  end

  # GET /securitys_transactions/1 or /securitys_transactions/1.json
  def show
  end

  # GET /securitys_transactions/new
  def new
    @securitys_transaction = SecuritysTransaction.new
  end

  # GET /securitys_transactions/1/edit
  def edit
  end

  # POST /securitys_transactions or /securitys_transactions.json
  def create
    @securitys_transaction = SecuritysTransaction.new(securitys_transaction_params)

    respond_to do |format|
      if @securitys_transaction.save
        format.html { redirect_to securitys_transaction_url(@securitys_transaction), notice: "Securitys transaction was successfully created." }
        format.json { render :show, status: :created, location: @securitys_transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @securitys_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /securitys_transactions/1 or /securitys_transactions/1.json
  def update
    respond_to do |format|
      if @securitys_transaction.update(securitys_transaction_params)
        format.html { redirect_to securitys_transaction_url(@securitys_transaction), notice: "Securitys transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @securitys_transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @securitys_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /securitys_transactions/1 or /securitys_transactions/1.json
  def destroy
    @securitys_transaction.destroy

    respond_to do |format|
      format.html { redirect_to securitys_transactions_url, notice: "Securitys transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_securitys_transaction
      @securitys_transaction = SecuritysTransaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def securitys_transaction_params
      params.require(:security_transactions).permit(:desc_transaction, :value_transaction, :date_transaction, :fund_id, :security_id, :quantity)
    end
end

app/helpers/securitys_transactions_helper.rb
module SecuritysTransactionsHelper
end

app/views/securitys_transactions/_form.html.erb
<%= form_with(model: securitys_transaction) do |form| %>
  <% if securitys_transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(securitys_transaction.errors.count, "error") %> prohibited this securitys_transaction from being saved:</h2>

      <ul>
        <% securitys_transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :desc_transaction, style: "display: block" %>
    <%= form.text_area :desc_transaction %>
  </div>

  <div>
    <%= form.label :value_transaction, style: "display: block" %>
    <%= form.text_field :value_transaction %>
  </div>

  <div>
    <%= form.label :date_transaction, style: "display: block" %>
    <%= form.date_field :date_transaction %>
  </div>

  <div>
    <%= form.label :fund_id, style: "display: block" %>
    <%= form.number_field :fund_id %>
  </div>

  <div>
    <%= form.label :security_id, style: "display: block" %>
    <%= form.number_field :security_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/securitys_transactions/_securitys_transaction.html.erb
<div id="<%= dom_id securitys_transaction %>">
  <p>
    <strong>Desc transaction:</strong>
    <%= securitys_transaction.desc_transaction %>
  </p>

  <p>
    <strong>Value transaction:</strong>
    <%= securitys_transaction.value_transaction %>
  </p>

  <p>
    <strong>Date transaction:</strong>
    <%= securitys_transaction.date_transaction %>
  </p>

  <p>
    <strong>Fund:</strong>
    <%= securitys_transaction.fund_id %>
  </p>

  <p>
    <strong>Security:</strong>
    <%= securitys_transaction.security_id %>
  </p>

</div>

app/views/securitys_transactions/edit.html.erb
<h1>Editing securitys transaction</h1>

<%= render "form", securitys_transaction: @securitys_transaction %>

<br>

<div>
  <%= link_to "Show this securitys transaction", @securitys_transaction %> |
  <%= link_to "Back to securitys transactions", securitys_transactions_path %>
</div>

app/views/securitys_transactions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Securitys transactions</h1>

<div id="securitys_transactions">
  <% @securitys_transactions.each do |securitys_transaction| %>
    <%= render securitys_transaction %>
    <p>
      <%= link_to "Show this securitys transaction", securitys_transaction %>
    </p>
  <% end %>
</div>

<%= link_to "New securitys transaction", new_securitys_transaction_path %>

app/views/securitys_transactions/new.html.erb
<h1>New securitys transaction</h1>

<%= render "form", securitys_transaction: @securitys_transaction %>

<br>

<div>
  <%= link_to "Back to securitys transactions", securitys_transactions_path %>
</div>

app/views/securitys_transactions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @securitys_transaction %>

<div>
  <%= link_to "Edit this securitys transaction", edit_securitys_transaction_path(@securitys_transaction) %> |
  <%= link_to "Back to securitys transactions", securitys_transactions_path %>

  <%= button_to "Destroy this securitys transaction", @securitys_transaction, method: :delete %>
</div>