config/routes.rb
Rails.application.routes.draw do
  resources :securitys_transactions
  resources :securitys_closing_prices
  resources :securities
  resources :cash_transactions
  resources :funds
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/fundos', to: 'funds#index'
  get '/transacaoCaixa', to: 'cash_transactions#index'
  get '/ativos', to: 'securities#index'

  get '/precoAtivos/:id/:date', to: 'securitys_closing_prices#getPrice'
  get '/precoAtivos/:id', to: 'securitys_closing_prices#getPrice'
  get '/precoAtivos', to: 'securitys_closing_prices#index'

  get '/transacaoAtivos', to: 'securitys_transactions#index'
  get "/precos/historico", to: "securitys_closing_prices#index"
  
  #portifolio

  #obter transacoes de caixa por fundo
  get "/portifolios/saldo/:id/:date", to: "portifolios#totalCashTransactions"
  get "/portifolios/saldo/:id", to: "portifolios#totalCashTransactions"
  get "/portifolios/transacoes/:id", to: "portifolios#listTransactionsByFund"
  get "/portifolios/transacoes/:id/:date", to: "portifolios#listTransactionsByFund"

  #obter ativos por fundo
  get "/portifolios/ativos/:id/:date", to: "portifolios#totalAtivos"
  get "/portifolios/ativos/:id", to: "portifolios#totalAtivos"

  #obter pl por fundo
  get "/portifolios/pl/:id/:date", to: "portifolios#PLfund"
  get "/portifolios/pl/:id", to: "portifolios#PLfund"
end

app/models/fund.rb
class Fund < ApplicationRecord
  has_many :cash_transactions, dependent: :delete_all
  has_many :securitys_transactions, dependent: :delete_all
  
  def as_json(_option)
    super({ 
      only: [:id, :name_fund, :desc_fund, :creation_date] 
    })
  end
end

app/controllers/funds_controller.rb
class FundsController < ApplicationController
  before_action :set_fund, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token
  # GET /funds or /funds.json
  def index
    render json: Fund.all
  end

  # GET /funds/1 or /funds/1.json
  def show
  end

  # GET /funds/new
  def new
    @fund = Fund.new
  end

  # GET /funds/1/edit
  def edit
  end

  # POST /funds or /funds.json
  def create
    @fund = Fund.new(fund_params)

    respond_to do |format|
      if @fund.save
        format.html { redirect_to fund_url(@fund), notice: "Fund was successfully created." }
        format.json { render :show, status: :created, location: @fund }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funds/1 or /funds/1.json
  def update
    respond_to do |format|
      if @fund.update(fund_params)
        format.html { redirect_to fund_url(@fund), notice: "Fund was successfully updated." }
        format.json { render :show, status: :ok, location: @fund }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funds/1 or /funds/1.json
  def destroy
    @fund = Fund.find(params[:id]);
    @fund.destroy

    respond_to do |format|
      format.html { redirect_to funds_url, notice: "Fund was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fund
      @fund = Fund.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fund_params
      params.require(:fund).permit(:name_fund, :desc_fund, :creation_date)
    end
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/views/funds/_form.html.erb
<%= form_with(model: fund) do |form| %>
  <% if fund.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(fund.errors.count, "error") %> prohibited this fund from being saved:</h2>

      <ul>
        <% fund.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name_fund, style: "display: block" %>
    <%= form.text_field :name_fund %>
  </div>

  <div>
    <%= form.label :desc_fund, style: "display: block" %>
    <%= form.text_area :desc_fund %>
  </div>

  <div>
    <%= form.label :creation_date, style: "display: block" %>
    <%= form.date_field :creation_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/funds/_fund.html.erb
<div id="<%= dom_id fund %>">
  <p>
    <strong>Name fund:</strong>
    <%= fund.name_fund %>
  </p>

  <p>
    <strong>Desc fund:</strong>
    <%= fund.desc_fund %>
  </p>

  <p>
    <strong>Creation date:</strong>
    <%= fund.creation_date %>
  </p>

</div>

app/views/funds/edit.html.erb
<h1>Editing fund</h1>

<%= render "form", fund: @fund %>

<br>

<div>
  <%= link_to "Show this fund", @fund %> |
  <%= link_to "Back to funds", funds_path %>
</div>

app/views/funds/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Funds</h1>

<div id="funds">
  <% @funds.each do |fund| %>
    <%= render fund %>
    <p>
      <%= link_to "Show this fund", fund %>
    </p>
  <% end %>
</div>

<%= link_to "New fund", new_fund_path %>

app/views/funds/new.html.erb
<h1>New fund</h1>

<%= render "form", fund: @fund %>

<br>

<div>
  <%= link_to "Back to funds", funds_path %>
</div>

app/views/funds/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @fund %>

<div>
  <%= link_to "Edit this fund", edit_fund_path(@fund) %> |
  <%= link_to "Back to funds", funds_path %>

  <%= button_to "Destroy this fund", @fund, method: :delete %>
</div>